### PR TITLE
fix the problem that dumpling panic when meeting an error at executing `--sql` 

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve? 
When `conf.SQL` is specified and query is failed, dumpling will panic.

### What is changed and how it works?
Check error before we use ir.

### Check List 

Tests 

 - Unit test
 - Integration test

Related changes

 - Need to cherry-pick to the release branch
 
### Release note

- fix the problem that dumpling panic when meeting an error at executing `--sql`

### CODE REVIEW

**Comment by overvenus** [comment]
Please add release note

**Review by kennytm — COMMENTED** [review]
LGTM

**Comment by lichunzhu** [comment]
reproduction:
./bin/dumpling -P 4000 --sql "test"
Release version: v4.0.9-5-gddc6354
Git commit hash: ddc6354e19d07a172f8478a9acc385751daba5d9
Git branch:      master
Build timestamp: 2021-01-14 07:52:12Z
Go version:      go version go1.13.4 darwin/amd64

[2021/01/14 15:53:11.809 +08:00] [INFO] [config.go:596] ["detect server type"] [type=TiDB]
[2021/01/14 15:53:11.809 +08:00] [INFO] [config.go:615] ["detect server version"] [version=4.0.0-beta.2-2009-g4088c2011-dirty]
[2021/01/14 15:53:11.810 +08:00] [WARN] [dump.go:767] ["If the amount of data to dump is large, criteria: (data more than 60GB or dumped time more than 10 minutes)\nyou'd better adjust the tikv_gc_life_time to avoid export failure due to TiDB GC during the dump process.\nBefore dumping: run sql `update mysql.tidb set VARIABLE_VALUE = '720h' where VARIABLE_NAME = 'tikv_gc_life_time';` in tidb.\nAfter dumping: run sql `update mysql.tidb set VARIABLE_VALUE = '10m' where VARIABLE_NAME = 'tikv_gc_life_time';` in tidb.\n"]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x14b965b]

goroutine 127 [running]:
sync.(*RWMutex).RLock(...)
        sync/rwmutex.go:48
database/sql.(*Rows).ColumnTypes(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        database/sql/sql.go:2861 +0x5b
github.com/pingcap/dumpling/v4/export.setTableMetaFromRows(0x0, 0x0, 0xc0000daa80, 0xc0006f24b0, 0x2ffffa0)
        github.com/pingcap/dumpling@/v4/export/ir.go:94 +0x40
github.com/pingcap/dumpling/v4/export.(*Writer).WriteTableData.func1(0x2ffffa0, 0xc0001ca120)
        github.com/pingcap/dumpling@/v4/export/writer.go:181 +0xadb
github.com/pingcap/br/pkg/utils.WithRetry(0x303f860, 0xc0000daa80, 0xc0005d7c70, 0x301ea20, 0xc0000f8ba0, 0xc000716c40, 0x100c8c8)
        github.com/pingcap/br@v0.0.0-20201119111016-600102357a27/pkg/utils/retry.go:34 +0x7c
github.com/pingcap/dumpling/v4/export.(*Writer).WriteTableData(0xc0000d8c00, 0x30607c0, 0xc00012c480, 0x303fd60, 0xc0000de0a0, 0x0, 0x1, 0x1)
        github.com/pingcap/dumpling@/v4/export/writer.go:161 +0x1d2
github.com/pingcap/dumpling/v4/export.(*Writer).handleTask(0xc0000d8c00, 0x2fffec0, 0xc0000a6540, 0x1, 0x1)
        github.com/pingcap/dumpling@/v4/export/writer.go:104 +0x31b
github.com/pingcap/dumpling/v4/export.(*Writer).run(0xc0000d8c00, 0xc0000d88a0, 0x0, 0x0)
        github.com/pingcap/dumpling@/v4/export/writer.go:86 +0x15c
github.com/pingcap/dumpling/v4/export.(*Dumper).startWriters.func4(0xc000017f68, 0x0)
        github.com/pingcap/dumpling@/v4/export/dump.go:253 +0x33
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0003f3e90, 0xc0001e32a0)
        golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:54 +0x66

**Review by lance6716 — APPROVED** [review]
LGTM

**Comment by glkappe** [comment]
asktug link：https://asktug.com/t/topic/67803/5

**Pull request merged**
