### PR TITLE
conf: support flagset in config

### PR DESCRIPTION
**Pull request by GMHDBJD**
### What problem does this PR solve? 
integrate flagset into export.config, so other components like dm can use flagset in dumpling too.

### CODE REVIEW

**Comment by lance6716** [comment]
Could you explain how DM will use `cfg.FlagSet`?

**Comment by GMHDBJD** [comment]
> Could you explain how DM will use `cfg.FlagSet`?

DM can use conf.ParseAndAdjust for extra args now. We now no need to change DM if dumpling add new argument.

**Comment by lance6716** [comment]
> > Could you explain how DM will use `cfg.FlagSet`?
> 
> DM can use conf.ParseAndAdjust for extra args now. We now no need to change DM if dumpling add new argument.

DM has saved some configuration in `subtaskCfg`, we still need to set them one by one? And will `ParseAndAdjust` overwrite some config to default value

**Comment by GMHDBJD** [comment]
previous use
```
dumpConfig := export.DefaultConfig()
dumpConfig.Host = db.Host
...
dumplingFlagSet = pflag.NewFlagSet
dumplingFlagSet.StringSliceVarP
...
dumplingFlagSet.Parse(args)
```

now
```
dumpConfig := export.DefaultConfig()
dumpConfig.Host = db.Host
...
dumplingFlagSet.Parse(args)
```

So now DM no need to update FlagSet when dumpling add new config.

> ParseAndAdjust overwrite some config to default value

That is expected behavior. If user specify the extra args for some arg, they should be overwritten.

**Comment by lance6716** [comment]
>>ParseAndAdjust overwrite some config to default value
>
>That is expected behavior. If user specify the extra args for some arg, they should be overwritten.

I mean 
```
dumpConfig := export.DefaultConfig()
dumpConfig.Host = db.Host
...
dumpConfig.ParseAndAdjust(args) // will reset host to flagset default value
```

**Comment by GMHDBJD** [comment]
> will reset host to flagset default value

`flagset.Parse(args)` will not overwrite value if it's not specified in args.
Others like `filesize`, which we set the values by `FlagSet.GetString()` will be overwritten with default value if not specified. I think that makes sense.

**Comment by lance6716** [comment]
> > will reset host to flagset default value
> 
> `flagset.Parse(args)` will not overwrite value if it's not specified in args.
> Others like `filesize`, which we set the values by `FlagSet.GetString()` will be overwritten with default value if not specified. I think that makes sense.

if user both set `filesize` in `chunk-filesize` and `extra-args`, and we promise `extra-args` has higher priority, then DM should first set `dumpConfig.FileSize` then `dumpConfig.ParseAndAdjust(args)`. 

But if user only set `chunk-filesize`, handling in above order will lost that value.

**Comment by GMHDBJD** [comment]
> if user both set `filesize` in `chunk-filesize` and `extra-args`, and we promise `extra-args` has higher priority, then DM should first set `dumpConfig.FileSize` then `dumpConfig.ParseAndAdjust(args)`.

You're right. I close the pr.

**Comment by lance6716** [comment]
we might find a way to let filesize behaves like host 🤣 will think of it later

**Pull request closed without merging**
