### PR TITLE
sql: fix table sample sql generator bug

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve? 
https://github.com/pingcap/dumpling/pull/260 introduced some bugs.

### What is changed and how it works?
Fix them.

### Check List 

Tests 

 - Unit test
 - Integration test

### Release note

- No release note

### CODE REVIEW

**Review by kennytm — COMMENTED** [review]
can you add a test case showing what is fixed by this?

**Comment by lichunzhu** [comment]
> can you add a test case showing what is fixed by this?

Already addressed, PTAL again.

**Pull request merged**
