### PR TITLE
rebuild mysql conn when retry failed chunks and support `trx-consistency-only` parameter

### PR DESCRIPTION
**Pull request by lichunzhu**
### What problem does this PR solve? 
https://github.com/pingcap/dumpling/issues/178
When we retry on failed chunks, if mysql connection is broken, the retry will fail directly and will take no effect.

### What is changed and how it works?
1. Add `trx-consistency-only` option. The default value is true. If it is `false`, dumpling won't release locks until the dumping progress is finished.
2. When dumpling retrys on failed chunks, we should rebuild MySQL connection when it was broken.
* For consistency none and consistency snapshot, we can rebuild MySQL connection directly since it doesn't assure consistent snapshot. But for consistency none we should update metadata after conn for DM when we build new MySQL conn.
* For consistency flush and consistency lock, we can rebuild MySQL connection only when dumpling hold locks during the whole dumping progress (`trx-consistency-only` = false). Before rebuilding MySQL connection we should also check that whether the mysql lock connection is still alive.

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
    Test kill the socket mysql connection. The connection can be rebuilt and dump data correctly.

Side effects

 - Increased code complexity

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 
### Release note

- Support `trx-consistency-only` parameter and support rebuild mysql connections during retry.

### CODE REVIEW

**Comment by lichunzhu** [comment]
Should be merged after https://github.com/pingcap/dumpling/pull/190

**Comment by kennytm** [comment]
i suggest we avoid the obscure abbreviation `trx`. 

since `--trx-consistency-only` in mydumper defaults to "false", while here we default to "true", i think we can pick a different name. `--transactional-consistency=0` or `--transactional-snapshot=0` or something.

**Comment by lichunzhu** [comment]
> i suggest we avoid the obscure abbreviation `trx`.
> 
> since `--trx-consistency-only` in mydumper defaults to "false", while here we default to "true", i think we can pick a different name. `--transactional-consistency=0` or `--transactional-snapshot=0` or something.

I think changing the name is okay, but we should keep this behavior the same as before, which means `--transactional-consistency` defaults to `1`.

**Comment by kennytm** [comment]
Yes the default should be 1.

**Review by kennytm — DISMISSED** [review]
LGTM

**Comment by lichunzhu** [comment]
fix some typo in https://github.com/pingcap/dumpling/pull/199/commits/91dcef296b33b9220e28c6c0deea33138e529798

**Review by kennytm — APPROVED** [review]

**Pull request merged**
