### PR TITLE
skip concurrent dump due to no valid smax or smin

### PR DESCRIPTION
**Pull request by jiyfhust**
### What problem does this PR solve? 

https://github.com/pingcap/dumpling/issues/186

### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation

### CODE REVIEW

**Comment by lichunzhu** [comment]
Could you please sign the CLA? [Contributor License Agreement](https://cla-assistant.io/pingcap/dumpling?pullRequest=189)

**Review by lichunzhu — APPROVED** [review]
LGTM

**Comment by jiyfhust** [comment]
Yes. I have signed it.

**Comment by lichunzhu** [comment]
OK, thanks a lot!

**Pull request merged**
