### PR TITLE
github: add challenge program template

### PR DESCRIPTION
**Pull request by hi-rustin**
### What problem does this PR solve? 

Add challenge program template.

### What is changed and how it works?

Add challenge program template.

### Check List 

Tests 
 - No code

Side effects

None

Related changes

None
 
### Release note

- No release note

### CODE REVIEW

**Comment by Rustin-Liu** [comment]
@kennytm  @lichunzhu  @AndreMouche  PTAL~

**Comment by Rustin-Liu** [comment]
It uses the [default-community-files](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-default-community-health-file#supported-file-types).

**Review by kennytm — COMMENTED** [review]
LGTM

**Comment by hi-rustin** [comment]
@lichunzhu  PTAL~ Thanks!

**Comment by hi-rustin** [comment]
ping~ @lichunzhu   @kennytm

**Review by lichunzhu — APPROVED** [review]
LGTM

**Pull request merged**
